# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gCxzv19I4scSKucEb4qu00Wht9Mtr-_g
"""

def kasallik_tashxisi(belgi):
  if belgi == "ko'gil aynishida":
    return "doprikin iching"
  elif belgi == "bosh og'rig'i":
    return "bolnol iching"
  elif belgi == "qon kamligida":
    return "metrid"
  elif belgi == "gripp":
    return "taylol hot iching"
  elif belgi == "tomoq og'rig'ida":
    return "septalete"
  elif belgi == "oyoq og'rig'i":
    return "kupen iching"
  elif belgi == "qorin dam bo'lganda":
    return "espumizam iching"
  elif belgi == "isitma":
    return "parasetamol iching"
  elif belgi == "qabziyat":
    return "dyufalak"
  elif belgi == "yiring":
    return "shifokorga murojat qiling"
  elif belgi == "bo'g'im og'rig'ida":
    return "sariq dalgit suring"
  elif belgi == "qon bosimida ":
    return "bisprilol iching"
  else:
    return "Shifokorga murojat qiling"
belgi=input("Kasallik belgisini kiriting ")
natija=kasallik_tashxisi(belgi)
print(natija)